"use client"
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Mlx4jGNkBbT
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card, CardFooter } from "@/components/ui/card"
import StorefrontIcon from "@mui/icons-material/Storefront";
import React, { useRef, useState } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import './globals.css'
import 'swiper/css/pagination';
import Image from "next/image";


export default function FavoriteShops({ stores }) {
  console.log(stores)
  return (
    (<div className="container flex flex-col min-h-screen ">
      <main className="flex-1 my-12 p-4 rounded-xl shadow-lg">
        <div className="grid  gap-6 md:gap-8 items-start">
          <div className="flex flex-col gap-2 items-center border-b border-fuchsia-800">
              <StorefrontIcon className='mt-1 text-4xl text-fuchsia-800'/>
              <h1 className="font-semibold text-2xl my-auto text-fuchsia-800 pb-4">المتاجر التي تتابعها</h1>
          </div>
          <div className="grid grid-cols-6 gap-6 md:gap-8 items-start overflow-hidden">
              <Swiper
                  slidesPerView={6}
                  centeredSlides={false}
                  grabCursor={true}
                  pagination={{clickable: true,
                  }}
                  className="mySwiper overflow-hidden flex justify-start"
              >   
              {stores.map((store) => (
                  <SwiperSlide key={store.id}>
                      <div className="grid gap-4 items-center ">
                          <Card className={"w-44"}>
                              <CardHeader className="border-b p-2">
                                  <div className="flex flex-col  items-center justify-center gap-4">
                                      <Image
                                          alt="Shop avatar"
                                          className="aspect-square rounded-full object-cover"
                                          height={80}
                                          src={store.store.storeImages}
                                          width={80}/>
                                      <div className="grid gap-1.5">
                                          <h2 className="font-bold text-2xl  text-center">{store.store.storeName}</h2>
                                      </div>
                                  </div>
                              </CardHeader>
                              <CardContent className="p-2">
                                  <Link href={`store-profile/id=${store.id}&store=${store.store.storeName}`}>
                                      <Button size="sm" variant="outline">
                                          زيارة 
                                      </Button>
                                  </Link>
                              </CardContent>
                          </Card>
                      </div>
                  </SwiperSlide>
              ))}
              </Swiper>
          </div>

          {/* <div className="grid gap-4 items-start">
            <h2 className="font-bold text-2xl text-slate-400 py-4 mr-4"> 📰  آخر الأخبار :</h2>
            <div className="grid gap-4 items-start">
              <Card>
                <CardContent className="p-4">
                  <div className="grid gap-4 items-start">
                    <div className="flex items-center gap-4">
                      <img
                          alt="Shop avatar"
                          className="rounded-full object-cover"
                          height="48"
                          src="/placeholder.svg"
                          style={{
                            aspectRatio: "48/48",
                            objectFit: "cover",
                          }}
                          width="48"/>
                      <div className="grid gap-0.5">
                        <h3 className="font-bold">Acme Fashion</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">2 hours ago</p>
                      </div>
                    </div>
                    <div className="grid gap-4 text-lg leading-loose">
                      <p>
                        Introducing the latest collection from Acme Fashion: Urban Chic. Embrace your style with these
                        trendy and versatile pieces. From statement tees to cool accessories, we've got everything you
                        need to elevate your wardrobe. Stay tuned for behind-the-scenes peeks and exclusive offers.
                        #AcmeFashion #UrbanChic
                      </p>
                    </div>
                    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4 items-start">
                      <img
                        alt="Post Image"
                        className="aspect-square rounded-lg object-cover border cursor-pointer"
                        height="150"
                        src="/placeholder.svg"
                        width="150" />
                      <img
                        alt="Post Image"
                        className="aspect-square rounded-lg object-cover border cursor-pointer"
                        height="150"
                        src="/placeholder.svg"
                        width="150" />
                      <img
                        alt="Post Image"
                        className="aspect-square rounded-lg object-cover border cursor-pointer"
                        height="150"
                        src="/placeholder.svg"
                        width="150" />
                      <img
                        alt="Post Image"
                        className="aspect-square rounded-lg object-cover border cursor-pointer"
                        height="150"
                        src="/placeholder.svg"
                        width="150" />
                    </div>
                  </div>
                </CardContent>
                <CardFooter className="border-t p-4">
                  <div className="flex items-center gap-4">
                    <Button className="w-8 h-8" size="icon" variant="outline">
                      <HeartIcon className="w-4 h-4" />
                      <span className="sr-only">Like</span>
                    </Button>
                    <Button className="w-8 h-8" size="icon" variant="outline">
                      <MessageCircleIcon className="w-4 h-4" />
                      <span className="sr-only">Comment</span>
                    </Button>
                  </div>
                </CardFooter>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <div className="grid gap-4 items-start">
                    <div className="flex items-center gap-4">
                      <img
                        alt="Shop avatar"
                        className="rounded-full object-cover"
                        height="48"
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "48/48",
                          objectFit: "cover",
                        }}
                        width="48" />
                      <div className="grid gap-0.5">
                        <h3 className="font-bold">Gourmet Delights</h3>
                        <p className="text-sm text-gray-500 dark:text-gray-400">5 hours ago</p>
                      </div>
                    </div>
                    <div className="grid gap-4 text-lg leading-loose">
                      <p>
                        Indulge in the art of gastronomy with Gourmet Delights. Our culinary experts have curated a
                        selection of mouth-watering recipes that will take your taste buds on a delightful journey. From
                        delectable appetizers to heavenly desserts, each dish is a masterpiece. Join us as we explore
                        the world of flavor and creativity. Are you ready to experience the magic of gourmet cuisine?
                        #GourmetDelights #CulinaryMasterpiece
                      </p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter className="border-t p-4">
                  <div className="flex items-center gap-4">
                    <Button className="w-8 h-8" size="icon" variant="outline">
                      <HeartIcon className="w-4 h-4" />
                      <span className="sr-only">Like</span>
                    </Button>
                    <Button className="w-8 h-8" size="icon" variant="outline">
                      <MessageCircleIcon className="w-4 h-4" />
                      <span className="sr-only">Comment</span>
                    </Button>
                  </div>
                </CardFooter>
              </Card>
            </div>
          </div> */}

        </div>
      </main>
    </div>)
  );
}


function PackageIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m7.5 4.27 9 5.15" />
      <path
        d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>)
  );
}


function HeartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>)
  );
}


function MessageCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 21 1.9-5.7a8.5 8.5 0 1 1 3.8 3.8z" />
    </svg>)
  );
}


function ShareIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>)
  );
}
