"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rvj1Ff3sKWq
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import InfoIcon from "@mui/icons-material/Info";
import Link from "next/link";
import { getOrders } from "@/lib/serverActions";
import { useEffect, useState } from "react";
import { format } from "date-fns";

export default function AllOrders() {
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    async function fetchOrdersData() {
      try {
        const data = await getOrders();
        if (data.success) {
          setOrders(data.orders);
        }
      } catch (error) {
        console.error("Error fetching orders:", error);
      }
    }

    fetchOrdersData();
  }, []);

  return (
    <div className="bg-white">
      <div className="pl-12 pr-72 py-8 h-auto w-auto my-12 ">
        <div className="relative px-4 py-10 mx-8 md:mx-0 sm:p-10 container mb-5 border border-fuchsia-800 shadow-md shadow-fuchsia-900 rounded-xl">
          <Card className="w-full h-full">
            <CardHeader className=" flex items-center gap-2 border-b border-fuchsia-800 mx-3 ">
              <CardTitle className={"pb-3 text-fuchsia-800"}>
                جميع الطلبيات
              </CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="mt-5 h-auto">
                <Table>
                  <TableHeader className="bg-fuchsia-200">
                    <TableRow>
                      <TableHead className="mx-auto text-center">
                        رقم الطلبية
                      </TableHead>
                      <TableHead className="text-center mx-auto">
                        العميل
                      </TableHead>
                      <TableHead className="hidden md:table-cell text-center">
                        تاريخ الطلبية
                      </TableHead>
                      <TableHead className="hidden sm:table-cell text-center">
                        تفاصيل
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {orders.map((order) => (
                      <TableRow key={order.id}>
                        <TableCell className="font-medium text-center">
                          # {order.id}{" "}
                        </TableCell>
                        <TableCell className="text-center">
                          {order.user}
                        </TableCell>
                        <TableCell className="hidden md:table-cell text-center">
                        {format(new Date(order.createdAt), "yyyy-MM-dd")}
                        </TableCell>
                        <TableCell className="hidden sm:table-cell text-center">
                          <Link href={`/dashboard/order/${order.id}`}>
                            <InfoIcon className={"text-fuchsia-600"} />
                          </Link>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
      <div className="text-center mt-16 text-slate-700 mr-80">
        <p>&copy; جميع الحقوق محفوظة لشركة بارع 2024</p>
      </div>
    </div>
  );
}
