"use client";
/**

 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rvj1Ff3sKWq
 */

import Menu from "@mui/material/Menu";
import MenuItem from "@mui/material/MenuItem";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from "@/components/ui/table";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getProducts, deleteProduct } from "@/lib/serverActions";
import Image from "next/image";

export default function Allproducte({ deleteProduct }) {
  const [products, setProducts] = useState([]);
  const [error, setError] = useState(null);

  const fetchProducts = async () => {
    try {
      const productData = await getProducts();
      if (!productData || !productData.products) {
        setProducts([]);
      } else {
        setProducts(productData.products);
      }
    } catch (err) {
      setError(err.message);
    }
  };

  useEffect(() => {
    fetchProducts();
  }, []);

  const [anchorEl, setAnchorEl] = useState(null);
  const [opens, setOpens] = useState(false);
  const handleClose = () => {
    setOpens(false);
    setAnchorEl(null);
  };
  const open = Boolean(anchorEl);
  const [selectedProductId, setSelectedProductId] = useState(null);

  const handleClick = (event, id) => {
    setAnchorEl(event.currentTarget);
    setSelectedProductId(id);
    setOpens(true);
  };

  const handleDelete = async (productId) => {
    try {
      await deleteProduct(productId);
      setProducts(products.filter((product) => product.id !== productId));
      // handleClose();
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <>
      <div className="pl-12 pr-72 py-8 h-auto w-auto my-12">
        <div className="container py-10 mb-5 border border-fuchsia-800 shadow-md shadow-fuchsia-900 rounded-xl">
          {error && <div className="text-red-500 mb-4">{error}</div>}
          <Card className="w-full h-full">
            <CardHeader className="flex items-center gap-2 border-b border-fuchsia-800 mx-3">
              <CardTitle className="pb-3 text-fuchsia-800">المنتجات</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="mt-5 h-auto mx-5">
                <Table>
                  <TableHeader className="bg-fuchsia-200">
                    <TableRow>
                      <TableHead className="mx-auto text-center">
                        المنتج
                      </TableHead>
                      <TableHead className="text-center mx-auto">
                        إسم المنتج
                      </TableHead>
                      <TableHead className="hidden md:table-cell text-center">
                        وصف المنتج
                      </TableHead>
                      <TableHead className="hidden sm:table-cell text-center">
                        السعر
                      </TableHead>
                      <TableHead className="hidden sm:table-cell text-center">
                        إجراءات
                      </TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {products.map((product) => (
                      <TableRow key={product.id} className="hover:bg-gray-100">
                        <TableCell className="font-medium text-center w-52">
                          <Image
                            src={product.image[0]}
                            className="placeholder='blur' my-auto rounded-sm h-24"
                            width={180}
                            height={200}
                            alt=""
                          />
                        </TableCell>
                        <TableCell className="text-center w-36">
                          {product.name}
                        </TableCell>
                        <TableCell className="hidden md:table-cell text-center w-auto">
                          {product.description}
                        </TableCell>
                        <TableCell className="hidden sm:table-cell text-center">
                          {product.price}
                        </TableCell>
                        <TableCell className="hidden sm:table-cell text-center">
                          <button
                            id="basic-button"
                            aria-controls={open ? "basic-menu" : undefined}
                            aria-haspopup="true"
                            aria-expanded={open ? "true" : undefined}
                            onClick={(event) => handleClick(event, product.id)}
                            className="no-underline mt-3 py-2 bg-fuchsia-700 hover:bg-fuchsia-800 text-white font-bold px-6 rounded-full shadow-lg shadow-neutral-950 transform transition-all duration-500 hover:scale-110"
                          >
                            إجراءات
                          </button>
                          <Menu
                            className="mt-2"
                            id="basic-menu"
                            anchorEl={anchorEl}
                            open={open}
                            onClose={handleClose}
                            MenuListProps={{
                              "aria-labelledby": "basic-button",
                            }}
                          >
                            <div className="w-24">
                              <Link
                                href={`/dashboard/all-products/${selectedProductId}`}
                              >
                                <MenuItem
                                  onClick={handleClose}
                                  className="hover:bg-slate-200 duration-600 no-underline"
                                >
                                  تعديل
                                </MenuItem>
                              </Link>
                            </div>
                            <div className="w-24">
                              <AlertDialog onClick={handleClose}>
                                <AlertDialogTrigger className="w-full">
                                  <MenuItem className="hover:bg-slate-200 duration-600">
                                    حذف
                                  </MenuItem>
                                </AlertDialogTrigger>
                                <AlertDialogContent>
                                  <AlertDialogHeader>
                                    <AlertDialogTitle>
                                      هل أنت متأكد أنك تريد حذف المنتج؟
                                    </AlertDialogTitle>
                                  </AlertDialogHeader>
                                  <AlertDialogFooter>
                                    <AlertDialogCancel>إلغاء</AlertDialogCancel>
                                    <AlertDialogAction
                                      className="bg-red-500 hover:bg-red-600"
                                      onClick={() =>
                                        handleDelete(selectedProductId)
                                      }
                                    >
                                      حذف
                                    </AlertDialogAction>
                                  </AlertDialogFooter>
                                </AlertDialogContent>
                              </AlertDialog>
                            </div>
                          </Menu>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
      <div className="text-center mt-16 text-slate-700 mr-80">
        <p>&copy; جميع الحقوق محفوظة لشركة بارع 2024</p>
      </div>
    </>
  );
}
