"use client";
/**

 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rvj1Ff3sKWq
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import Image from "next/image";
import basket from "../../../public/images/basket.png";
export default function EmptyOrder() {
  return (
    <div className="bg-white">
      <div className="pl-12 pr-72 py-8 h-auto w-auto my-12 ">
        <div className="relative px-4 py-10 mx-8  md:mx-0 sm:p-10 container mb-5 border border-fuchsia-800 shadow-md shadow-fuchsia-900 rounded-xl">
          <Card className="w-full h-full">
            <CardHeader className=" flex items-center gap-2 border-b border-fuchsia-800 mx-3 ">
              <CardTitle className={"pb-3 text-fuchsia-800"}>
                جميع الطلبات
              </CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className=" mt-5 h-auto text-center">
                <Image
                  src={basket}
                  alt=""
                  width={200}
                  height={120}
                  className=" mx-80 "
                />
                <p className=" text-slate-600 text-lg mb-12">
                  {" "}
                  لا يوجد لديك طلبات
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
      <div className="text-center mt-16 text-slate-700 mr-80">
        <p>&copy; جميع الحقوق محفوظة لشركة بارع 2024</p>
      </div>
    </div>
  );
}
